package com.utopia.core.security.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToMany;

import com.utopia.core.model.SoftDeletePersistentSupport;

/**
 * AbstractCoApplication generated by Mehdi
 */
@MappedSuperclass
public abstract class AbstractCoApplication extends SoftDeletePersistentSupport implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -235908653141048628L;
	private String name;
	private String secretKey;
	private int tokenValidity;
	
	private Set<CoUserAppToken> coUserAppTokens = new HashSet<CoUserAppToken>(0);
	private Set<CoAppUscsAccss> coAppUscsAccsses = new HashSet<CoAppUscsAccss>(
			0);
	private String scope;
	private String redirectURL;
	// Constructors

	/** default constructor */
	public AbstractCoApplication() {
	}


	@Column(name = "NAME", unique = true, nullable = false, insertable = true, updatable = true, length = 3000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SECRET_KEY", unique = false, nullable = false, insertable = true, updatable = true, length = 3000)
	public String getSecretKey() {
		return this.secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "coApplication")
	public Set<CoUserAppToken> getCoUserAppTokens() {
		return this.coUserAppTokens;
	}

	public void setCoUserAppTokens(Set<CoUserAppToken> coUserAppTokens) {
		this.coUserAppTokens = coUserAppTokens;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "coApplication")
	public Set<CoAppUscsAccss> getCoAppUscsAccsses() {
		return this.coAppUscsAccsses;
	}

	public void setCoAppUscsAccsses(Set<CoAppUscsAccss> coAppUscsAccsses) {
		this.coAppUscsAccsses = coAppUscsAccsses;
	}

	@Column(name="TOKEN_VALIDITY")
	public int getTokenValidity() {
		return tokenValidity;
	}


	public void setTokenValidity(int tokenValidity) {
		this.tokenValidity = tokenValidity;
	}

	@Column
	public String getScope() {
		return scope;
	}


	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name="redirect_URL")
	public String getRedirectURL() {
		return redirectURL;
	}


	public void setRedirectURL(String redirectURL) {
		this.redirectURL = redirectURL;
	}

	
}