package com.utopia.core.security.model;

// Generated by Mehdi

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.UniqueConstraint;

/**
 * CoAppUscsAccss 
 */
@Entity
@Table(name = "CO_APP_USCS_ACCSS", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CO_USECASE_ID", "CO_APPLICATION_ID" }) })
@TableGenerator(name = "CoAppUscsAccssSequenceGenerator", 
	table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CO_APP_USCS_ACCSS")
public class CoAppUscsAccss extends AbstractCoAppUscsAccss implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 5748893547877854487L;

	/** default constructor */
	public CoAppUscsAccss() {
	}

	/** minimal constructor */
	public CoAppUscsAccss(Long coAppUscsAccssId, CoApplication coApplication) {
		super(coAppUscsAccssId, coApplication);
	}


}
