package com.utopia.core.security.model;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CoPortalSysAccss 
 */
@Entity
@Table(name = "CO_PORTAL_SYS_ACCSS", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"CO_PORTAL_ID", "CM_SYSTEM_ID", "CM_SUBSYSTEM_ID" }) })
public class CoPortalSysAccss extends AbstractCoPortalSysAccss implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 3190368710189295884L;

	/** default constructor */
	public CoPortalSysAccss() {
	}

}
