package com.utopia.core.security.model;

// Generated by MyEclipse Persistence Tools

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.UniqueConstraint;

/**
 * CoPortal 
 */
@Entity
@Table(name = "CO_PORTAL", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "DOMAIN_NAME" }),
		@UniqueConstraint(columnNames = { "NAME" }) })
@TableGenerator(name = "PortalSequenceGenerator", 
table = "CO_SEQUENCE", pkColumnName = "TABLENAME", valueColumnName = "CURRENTID", pkColumnValue = "CO_PORTAL")
public class CoPortal extends AbstractCoPortal implements java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 748258279291366610L;

	/** default constructor */
	public CoPortal() {
	}

}
