package com.utopia.core.model;

// Generated by Mehdi

import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CoUserAppToken generated by Mehdi
 */
@Entity
@Table(name = "CO_USER_APP_TOKEN",  uniqueConstraints = {})
@NamedQueries({@NamedQuery(name= CoUserAppToken.FIND_APPLICATION_BY_TOKEN,query="SELECT CoUserAppToken FROM CoUserAppToken CoUserAppToken WHERE CoUserAppToken.token=:token "
		+ "AND CoUserAppToken.validTo>CURRENT_TIMESTAMP ")})
public class CoUserAppToken extends AbstractCoUserAppToken implements
		java.io.Serializable {

	// Constructors
	public static final String FIND_APPLICATION_BY_TOKEN="findApplicatonByToken";
	/**
	 * 
	 */
	private static final long serialVersionUID = 3210024808072199484L;

	/** default constructor */
	public CoUserAppToken() {
	}

	
}
