package com.utopia.core.model;

// Generated by Mehdi

import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author Mehdi
 */
@Entity
@Table(name = "CO_USER_APP_TOKEN",  uniqueConstraints = {})
@NamedQueries({@NamedQuery(name= UserAppToken.FIND_APPLICATION_BY_TOKEN,query="SELECT UserAppToken FROM UserAppToken UserAppToken WHERE UserAppToken.token=:token "
		+ "AND UserAppToken.validTo>CURRENT_TIMESTAMP ")})
public class UserAppToken extends AbstractUserAppToken implements
		java.io.Serializable {

	// Constructors
	public static final String FIND_APPLICATION_BY_TOKEN="findApplicatonByToken";
	/**
	 * 
	 */
	private static final long serialVersionUID = 3210024808072199484L;

	/** default constructor */
	public UserAppToken() {
	}

	
}
